modLoader="javafml"
loaderVersion="[47,)"
license="APACHE"

[[mods]]
modId="${addon_mod_id}"
version="${addon_version}"
displayName="${addon_mod_name}"
authors="${addon_mod_authors}"
description='''${addon_mod_description}'''

[[dependencies.${addon_mod_id}]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.${addon_mod_id}]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"

[[dependencies.${addon_mod_id}]]
modId="justlevelingfork"
mandatory=true
versionRange="[${base_mod_version}]"
ordering="AFTER"
side="BOTH"

[[dependencies.${addon_mod_id}]]
modId="kubejs"
mandatory=true
versionRange="[2001,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${addon_mod_id}]]
modId="rhino"
mandatory=true
versionRange="[2001,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${addon_mod_id}]]
modId="cloth_config"
mandatory=true
versionRange="[11,)"
ordering="AFTER"
side="CLIENT"

[[dependencies.${addon_mod_id}]]
modId="legendarytabs"
mandatory=true
versionRange="[1.0,)"
ordering="AFTER"
side="CLIENT"
